// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/19/2026, 5:27:03 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/mnt/c/Users/Cornaa/Downloads/portfolio-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/mnt/c/Users/Cornaa/Downloads/portfolio-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/mnt/c/Users/Cornaa/Downloads/portfolio-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/mnt/c/Users/Cornaa/Downloads/portfolio-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/mnt/c/Users/Cornaa/Downloads/portfolio-nuxt/plugins/**/*.{js,ts,mjs}","/mnt/c/Users/Cornaa/Downloads/portfolio-nuxt/composables/**/*.{js,ts,mjs}","/mnt/c/Users/Cornaa/Downloads/portfolio-nuxt/utils/**/*.{js,ts,mjs}","/mnt/c/Users/Cornaa/Downloads/portfolio-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/mnt/c/Users/Cornaa/Downloads/portfolio-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/mnt/c/Users/Cornaa/Downloads/portfolio-nuxt/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;